# Generated by Django 3.2.20 on 2023-07-14 20:27

from django.db import migrations, models
from phone_field import PhoneField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_text', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=25,blank=False)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
                ('phone_num', PhoneField(blank=True)),
                ('address', models.CharField(max_length=25)),
                # ('id', models.AutoField(primary_key=True)),
            ],
        ),
    ]
