# Generated by Django 3.2.20 on 2023-07-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='home_text',
        ),
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='home',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
