# Generated by Django 3.2.20 on 2023-07-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage_main', '0002_auto_20230718_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='home',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
