# Generated by Django 3.2.20 on 2023-07-17 20:56

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage_main', '0003_auto_20230718_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='phone_num',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
