# Generated by Django 3.2.20 on 2023-07-31 20:34

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage_main', '0004_alter_home_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='address',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='phone_num',
            field=phone_field.models.PhoneField(blank=True, max_length=10, null=True),
        ),
    ]
